
package imse.soc.grp4.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1.6
 * 
 */
@XmlRootElement(name = "InvalidProductIdFault", namespace = "http://imse.soc.grp4.org/inventoryservice")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvalidProductIdFault", namespace = "http://imse.soc.grp4.org/inventoryservice")
public class InvalidProductIdFaultBean {

    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
