
package org.grp4.soc.imse.inventoryservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidProductIdFault", targetNamespace = "http://imse.soc.grp4.org/inventoryservice")
public class InvalidProductIdFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidProductIdFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidProductIdFault_Exception(String message, InvalidProductIdFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidProductIdFault_Exception(String message, InvalidProductIdFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.grp4.soc.imse.inventoryservice.InvalidProductIdFault
     */
    public InvalidProductIdFault getFaultInfo() {
        return faultInfo;
    }

}
