
package org.grp4.soc.imse.inventoryservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventoryService", targetNamespace = "http://imse.soc.grp4.org/inventoryservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventoryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws InvalidProductIdFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductAvailability", targetNamespace = "http://imse.soc.grp4.org/inventoryservice", className = "org.grp4.soc.imse.inventoryservice.GetProductAvailability")
    @ResponseWrapper(localName = "getProductAvailabilityResponse", targetNamespace = "http://imse.soc.grp4.org/inventoryservice", className = "org.grp4.soc.imse.inventoryservice.GetProductAvailabilityResponse")
    @Action(input = "http://imse.soc.grp4.org/inventoryservice/InventoryService/getProductAvailabilityRequest", output = "http://imse.soc.grp4.org/inventoryservice/InventoryService/getProductAvailabilityResponse", fault = {
        @FaultAction(className = InvalidProductIdFault_Exception.class, value = "http://imse.soc.grp4.org/inventoryservice/InventoryService/getProductAvailability/Fault/InvalidProductIdFault")
    })
    public String getProductAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws InvalidProductIdFault_Exception
    ;

}
