
package acme;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "acme", targetNamespace = "http://acme", wsdlLocation = "http://localhost:9090/ode/processes/acme?wsdl")
public class Acme
    extends Service
{

    private final static URL ACME_WSDL_LOCATION;
    private final static WebServiceException ACME_EXCEPTION;
    private final static QName ACME_QNAME = new QName("http://acme", "acme");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/ode/processes/acme?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACME_WSDL_LOCATION = url;
        ACME_EXCEPTION = e;
    }

    public Acme() {
        super(__getWsdlLocation(), ACME_QNAME);
    }

    public Acme(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACME_QNAME, features);
    }

    public Acme(URL wsdlLocation) {
        super(wsdlLocation, ACME_QNAME);
    }

    public Acme(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACME_QNAME, features);
    }

    public Acme(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Acme(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AcmePortType
     */
    @WebEndpoint(name = "acmeSOAP11port_http")
    public AcmePortType getAcmeSOAP11PortHttp() {
        return super.getPort(new QName("http://acme", "acmeSOAP11port_http"), AcmePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcmePortType
     */
    @WebEndpoint(name = "acmeSOAP11port_http")
    public AcmePortType getAcmeSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://acme", "acmeSOAP11port_http"), AcmePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACME_EXCEPTION!= null) {
            throw ACME_EXCEPTION;
        }
        return ACME_WSDL_LOCATION;
    }

}
