
package acme;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "acmePortType", targetNamespace = "http://acme")
@XmlSeeAlso({
    acme.ObjectFactory.class,
    org.grp4.soc.imse.inventoryservice.ObjectFactory.class
})
public interface AcmePortType {


    /**
     * 
     * @param weight
     * @param address
     * @param orderid
     * @param date
     * @param type
     * @param out
     */
    @WebMethod(action = "http://acme/shipment")
    @RequestWrapper(localName = "shipment", targetNamespace = "http://acme", className = "acme.Shipment")
    @ResponseWrapper(localName = "shipmentResponse", targetNamespace = "http://acme", className = "acme.ShipmentResponse")
    public void shipment(
        @WebParam(name = "address", targetNamespace = "http://acme")
        String address,
        @WebParam(name = "type", targetNamespace = "http://acme")
        int type,
        @WebParam(name = "weight", targetNamespace = "http://acme")
        float weight,
        @WebParam(name = "orderid", targetNamespace = "http://acme")
        int orderid,
        @WebParam(name = "out", targetNamespace = "http://acme", mode = WebParam.Mode.OUT)
        Holder<String> out,
        @WebParam(name = "date", targetNamespace = "http://acme", mode = WebParam.Mode.OUT)
        Holder<String> date);

    /**
     * 
     * @param amount
     * @param address
     * @param name
     * @param cvc
     * @param cardnumber
     * @param orderid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://acme/payment")
    @WebResult(name = "out", targetNamespace = "http://acme")
    @RequestWrapper(localName = "payment", targetNamespace = "http://acme", className = "acme.Payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "http://acme", className = "acme.PaymentResponse")
    public String payment(
        @WebParam(name = "orderid", targetNamespace = "http://acme")
        int orderid,
        @WebParam(name = "name", targetNamespace = "http://acme")
        String name,
        @WebParam(name = "address", targetNamespace = "http://acme")
        String address,
        @WebParam(name = "amount", targetNamespace = "http://acme")
        float amount,
        @WebParam(name = "cardnumber", targetNamespace = "http://acme")
        long cardnumber,
        @WebParam(name = "cvc", targetNamespace = "http://acme")
        int cvc);

    /**
     * 
     * @param payload
     * @return
     *     returns acme.AcmeResponse
     */
    @WebMethod(action = "http://acme/process")
    @WebResult(name = "acmeResponse", targetNamespace = "http://acme", partName = "payload")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AcmeResponse process(
        @WebParam(name = "acmeRequest", targetNamespace = "http://acme", partName = "payload")
        AcmeRequest payload);

}
